"""NCAA psych sheet PDF parser.

Supported format:
    NCAA Division I psych sheet PDFs generated by ActiveReports / similar.
    Two-column layout with entries per event. Each entry row has format:
        Rank  Last, First  Year  Team  QS  SeedTime[w]

    The 'w' suffix indicates a wildcard/secondary qualifier.
    "INVITED" separator lines divide auto-qualifiers from invitees.

    Event headers: "Event N  Men/Women  EventName"
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

import pdfplumber

from workers.parsers.models import ParsedRow
from workers.parsers.ncaa_results import time_to_centiseconds

logger = logging.getLogger(__name__)

EVENT_HEADER_RE = re.compile(
    r"^Event\s+(\d+)\s+(Men|Women)\s+(.+)$", re.IGNORECASE
)

ENTRY_ROW_RE = re.compile(
    r"^\s*(\d+)\s+"              # rank
    r"([A-Z][A-Za-z'-]+(?:\s+[A-Z][A-Za-z'-]+)*),\s*"  # last name(s), followed by comma
    r"([A-Za-z'-]+(?:\s+[A-Za-z'-]+)*)\s+"              # first name(s)
    r"(FR|SO|JR|SR|Grad|5Y)\s+"  # year/eligibility
    r"(.+?)\s+"                  # team (greedy-minimal, stops at QS/std)
    r"(?:QS|QT|QA|B|I)\s+"      # qualifying standard marker
    r"(\d+:[\d.]+|\d+\.\d+)"    # seed time
    r"(w)?\s*$"                  # optional wildcard suffix
)

SKIP_PATTERNS = (
    re.compile(r"^-+\s*INVITED\s*-+", re.IGNORECASE),
    re.compile(r"^Name\s+Elig", re.IGNORECASE),
    re.compile(r"^Selections Psych Sheet"),
    re.compile(r"^Page\s+\d+"),
    re.compile(r"^\d+/\d+/\d+\s+\d+:\d+"),
    re.compile(r"^w$"),
    re.compile(r"^\s*$"),
)

YEAR_ABBREVS = {"FR", "SO", "JR", "SR", "Grad", "5Y"}


def _extract_columns(pdf_path: Path) -> list[str]:
    """Extract text from a two-column PDF, processing each column separately."""
    all_lines: list[str] = []

    with pdfplumber.open(str(pdf_path)) as pdf:
        for page in pdf.pages:
            mid = page.width / 2
            left = page.crop((0, 0, mid, page.height))
            right = page.crop((mid, 0, page.width, page.height))

            left_text = left.extract_text() or ""
            right_text = right.extract_text() or ""

            all_lines.extend(left_text.splitlines())
            all_lines.extend(right_text.splitlines())

    return all_lines


def parse_psych_sheet(pdf_path: Path) -> list[ParsedRow]:
    """Parse an NCAA psych sheet PDF into structured entry rows.

    Returns ParsedRow objects with seed_time_cs populated (no final_time_cs
    since psych sheets only have seed times, not results).
    """
    lines = _extract_columns(pdf_path)
    rows: list[ParsedRow] = []

    current_event_number: int | None = None
    current_event_name: str | None = None
    current_gender: str | None = None

    for line_num, line in enumerate(lines, start=1):
        line = line.strip()
        if not line:
            continue

        if any(p.match(line) for p in SKIP_PATTERNS):
            continue

        header_match = EVENT_HEADER_RE.match(line)
        if header_match:
            current_event_number = int(header_match.group(1))
            gender_word = header_match.group(2).lower()
            current_gender = "M" if gender_word == "men" else "F"
            current_event_name = header_match.group(3).strip()
            logger.debug(
                "Event %d: %s %s", current_event_number, current_gender, current_event_name
            )
            continue

        if current_event_number is None:
            continue

        row_match = ENTRY_ROW_RE.match(line)
        if not row_match:
            logger.debug("Skipping line %d: %r", line_num, line[:80])
            continue

        rank_str, last_name, first_name, year, team, time_str, wildcard = row_match.groups()

        try:
            seed_cs = time_to_centiseconds(time_str)
            row = ParsedRow(
                event_number=current_event_number,
                event_name=current_event_name,  # type: ignore[arg-type]
                athlete_first_name=first_name.strip(),
                athlete_last_name=last_name.strip(),
                team=team.strip(),
                gender=current_gender,  # type: ignore[arg-type]
                seed_time_cs=seed_cs,
                final_time_cs=None,
                place=None,
                result_status="official",
            )
            rows.append(row)
        except Exception as exc:
            logger.warning("Malformed row at line %d: %s — %r", line_num, exc, line[:80])
            continue

    logger.info("Parsed %d psych sheet entries from %s", len(rows), pdf_path)
    return rows
