"""initial schema

Revision ID: 10ca8b1425c4
Revises: 
Create Date: 2026-08-09 15:19:20.106955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ca8b1425c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('team_display', sa.String(length=256), nullable=False),
    sa.Column('team_key', sa.String(length=128), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athletes_team_key'), 'athletes', ['team_key'], unique=False)
    op.create_table('events',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('stroke', sa.String(length=32), nullable=False),
    sa.Column('distance', sa.SmallInteger(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meets',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('leagues',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('meet_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meet_id'], ['meets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_meet_id'), 'leagues', ['meet_id'], unique=False)
    op.create_index(op.f('ix_leagues_owner_id'), 'leagues', ['owner_id'], unique=False)
    op.create_table('meet_events',
    sa.Column('meet_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('event_number', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['meet_id'], ['meets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meet_id', 'event_number', name='uq_meet_events_meet_number')
    )
    op.create_index(op.f('ix_meet_events_event_id'), 'meet_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_meet_events_meet_id'), 'meet_events', ['meet_id'], unique=False)
    op.create_table('league_members',
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_league_members_league_user')
    )
    op.create_index(op.f('ix_league_members_league_id'), 'league_members', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_members_user_id'), 'league_members', ['user_id'], unique=False)
    op.create_table('meet_entries',
    sa.Column('meet_event_id', sa.BigInteger(), nullable=False),
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('seed_time_cs', sa.Integer(), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('entry_status', sa.String(length=16), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['meet_event_id'], ['meet_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meet_event_id', 'athlete_id', name='uq_meet_entries_event_athlete')
    )
    op.create_index(op.f('ix_meet_entries_athlete_id'), 'meet_entries', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_meet_entries_meet_event_id'), 'meet_entries', ['meet_event_id'], unique=False)
    op.create_table('results',
    sa.Column('meet_event_id', sa.BigInteger(), nullable=False),
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('final_time_cs', sa.Integer(), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('result_status', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_uri', sa.String(length=512), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['meet_event_id'], ['meet_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meet_event_id', 'athlete_id', name='uq_results_event_athlete')
    )
    op.create_index(op.f('ix_results_athlete_id'), 'results', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_results_meet_event_id'), 'results', ['meet_event_id'], unique=False)
    op.create_table('roster_picks',
    sa.Column('league_member_id', sa.BigInteger(), nullable=False),
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('pick_number', sa.SmallInteger(), nullable=False),
    sa.Column('picked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['league_member_id'], ['league_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_member_id', 'athlete_id', name='uq_roster_picks_member_athlete')
    )
    op.create_index(op.f('ix_roster_picks_athlete_id'), 'roster_picks', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_roster_picks_league_member_id'), 'roster_picks', ['league_member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roster_picks_league_member_id'), table_name='roster_picks')
    op.drop_index(op.f('ix_roster_picks_athlete_id'), table_name='roster_picks')
    op.drop_table('roster_picks')
    op.drop_index(op.f('ix_results_meet_event_id'), table_name='results')
    op.drop_index(op.f('ix_results_athlete_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_meet_entries_meet_event_id'), table_name='meet_entries')
    op.drop_index(op.f('ix_meet_entries_athlete_id'), table_name='meet_entries')
    op.drop_table('meet_entries')
    op.drop_index(op.f('ix_league_members_user_id'), table_name='league_members')
    op.drop_index(op.f('ix_league_members_league_id'), table_name='league_members')
    op.drop_table('league_members')
    op.drop_index(op.f('ix_meet_events_meet_id'), table_name='meet_events')
    op.drop_index(op.f('ix_meet_events_event_id'), table_name='meet_events')
    op.drop_table('meet_events')
    op.drop_index(op.f('ix_leagues_owner_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_meet_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_table('users')
    op.drop_table('meets')
    op.drop_table('events')
    op.drop_index(op.f('ix_athletes_team_key'), table_name='athletes')
    op.drop_table('athletes')
    # ### end Alembic commands ###
